FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install

ENV REACT_APP_NEWS_API_API_BASE_URL=""
ENV REACT_APP_NEW_YORK_TIME_API_BASE_URL=""
ENV REACT_APP_NEW_YORK_TIME_API_IMAGE_URL=""
ENV REACT_APP_THE_GUARDIAN_API_BASE_URL=""
ENV REACT_APP_NEWS_API_API_KEY=""
ENV REACT_APP_NEW_YORK_TIME_API_KEY=""
ENV REACT_APP_THE_GUARDIAN_API_KEY=""

EXPOSE 3000

CMD ["npm", "start"]
